---
Name: text-target-length
---
SilverStripe\Forms\TextareaField:
  extensions:
    - JonoM\SilverStripeTextTargetLength\TextTargetLengthExtension
SilverStripe\Forms\TextareaField:
  extensions:
    - JonoM\SilverStripeTextTargetLength\TextTargetLengthExtension
SilverStripe\Forms\HTMLEditor\HTMLEditorField:
  extensions:
    - JonoM\SilverStripeTextTargetLength\TextTargetLengthExtension
